version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baseUsers
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --init-file /docker-entrypoint-initdb.d/db.sql
    networks:
      - apiteste
  
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    environment:
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - apiteste

networks:
  apiteste:
    driver: bridge